services:

  Doctrine\ORM\EntityManager:
    factory: [CodelyTv\Mooc\Shared\Infrastructure\Doctrine\MoocEntityManagerFactory, create]
    arguments:
      - driver:   '%env(MOOC_DATABASE_DRIVER)%'
        host:     'codelytv-php_ddd_basic_skeleton-mooc-mysql'
        port:     '%env(MOOC_DATABASE_PORT)%'
        dbname:   '%env(MOOC_DATABASE_NAME)%'
        user:     '%env(MOOC_DATABASE_USER)%'
        password: '%env(MOOC_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: codely.database_connection }
    public: true
